In [157]:
import pandas as pd

data  = pd.read_csv('../home_insight.csv')
data1 = pd.read_csv('../home_insight2.csv')
data2 = pd.read_csv('../home_insight3.csv')

pd.options.display.max_columns = None

Number of player assignation to specific positions occured based on their speed

In [158]:
display(data)

,# LBv,LBh,LBs,CBv,CBh,CBs,RBv,RBh,RBs,LMv,LMh,LMs,CMv,CMh,CMs,RMv,RMh,RMs,ACMv,ACMh,ACMs,LFv,LFh,LFs,CFv,CFh,CFs,RFv,RFh,RFs
0,4056.0,686.0,626.0,8182.0,1484.0,1534.0,4061.0,631.0,789.0,3311.0,677.0,694.0,8499.0,1708.0,1919.0,2922.0,414.0,524.0,2759.0,477.0,724.0,95.0,28.0,57.0,5217.0,843.0,1047.0,33.0,5.0,22.0
1,742.0,165.0,113.0,1602.0,292.0,256.0,759.0,124.0,137.0,615.0,167.0,177.0,2335.0,437.0,525.0,275.0,74.0,72.0,139.0,52.0,50.0,0.0,0.0,0.0,753.0,128.0,140.0,0.0,0.0,0.0
2,2317.0,460.0,525.0,6616.0,1506.0,1461.0,2926.0,656.0,600.0,2833.0,725.0,740.0,4851.0,1328.0,1471.0,1956.0,530.0,563.0,793.0,186.0,164.0,291.0,89.0,85.0,3323.0,725.0,787.0,601.0,129.0,170.0
3,1611.0,339.0,461.0,6697.0,1605.0,1729.0,1593.0,365.0,389.0,2932.0,657.0,693.0,5668.0,1315.0,1444.0,3417.0,727.0,746.0,2072.0,421.0,482.0,2795.0,604.0,583.0,6859.0,1634.0,1561.0,2800.0,583.0,721.0
4,4686.0,967.0,1055.0,7132.0,1339.0,1585.0,3492.0,659.0,725.0,3241.0,714.0,818.0,9864.0,2184.0,2398.0,1952.0,442.0,471.0,1089.0,196.0,268.0,82.0,18.0,21.0,5233.0,1090.0,1134.0,1343.0,185.0,211.0
5,3329.0,802.0,859.0,9070.0,1700.0,1896.0,3779.0,614.0,777.0,3292.0,691.0,827.0,8224.0,1852.0,2432.0,2500.0,534.0,676.0,1071.0,241.0,309.0,405.0,91.0,164.0,3835.0,690.0,705.0,98.0,36.0,46.0
6,3193.0,768.0,738.0,8885.0,2018.0,2098.0,2761.0,649.0,629.0,3217.0,912.0,871.0,6508.0,1580.0,1683.0,3867.0,971.0,989.0,1259.0,288.0,332.0,0.0,0.0,0.0,5477.0,1515.0,1609.0,401.0,92.0,108.0
7,3122.0,626.0,935.0,6996.0,1536.0,1733.0,3329.0,596.0,696.0,3276.0,554.0,552.0,4543.0,1225.0,1554.0,3595.0,514.0,814.0,1544.0,352.0,445.0,156.0,8.0,17.0,3902.0,727.0,894.0,484.0,57.0,101.0
8,4019.0,1009.0,1056.0,10133.0,2581.0,2420.0,4188.0,1001.0,1256.0,3607.0,564.0,654.0,7042.0,1741.0,2101.0,1287.0,274.0,398.0,293.0,60.0,67.0,953.0,217.0,209.0,4575.0,991.0,1211.0,510.0,165.0,165.0
9,3200.0,711.0,914.0,10819.0,1943.0,2168.0,3383.0,539.0,782.0,2316.0,450.0,515.0,8280.0,1630.0,2512.0,2214.0,387.0,459.0,316.0,75.0,151.0,2176.0,288.0,417.0,4380.0,706.0,699.0,2791.0,396.0,378.0

Number of player role assignation occured

In [159]:
display(data1)

,# LB,CB,RB,LM,CM,RM,ACM,LF,CF,RF
0,4408.0,10901.0,4288.0,4129.0,9884.0,3455.0,1666.0,984.0,6237.0,1262.0

Avrg number of player role assignation occured

In [160]:
display(data2)

,# LB,CB,RB,LM,CM,RM,ACM,LF,CF,RF
0,4417.0,13250.0,4153.0,4096.0,11205.0,4521.0,2086.0,1408.0,7375.0,1856.0